name: unit-tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 21]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Test with Maven
        run: mvn test
